/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_NOPMAP_H_RPCGEN
#define _TEST_NOPMAP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TESTPROG 0x20008000
#define TESTPROG_VERS1 1

#if defined(__STDC__) || defined(__cplusplus)
#define test_hello 1
extern  char ** test_hello_1(char **, CLIENT *);
extern  char ** test_hello_1_svc(char **, struct svc_req *);
#define test_ctime 2
extern  char ** test_ctime_1(void *, CLIENT *);
extern  char ** test_ctime_1_svc(void *, struct svc_req *);
extern int testprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define test_hello 1
extern  char ** test_hello_1();
extern  char ** test_hello_1_svc();
#define test_ctime 2
extern  char ** test_ctime_1();
extern  char ** test_ctime_1_svc();
extern int testprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_NOPMAP_H_RPCGEN */
