/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_BATCH_H_RPCGEN
#define _TEST_BATCH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TESTPROG 0x20008000
#define TESTPROG_VERS1 1

#if defined(__STDC__) || defined(__cplusplus)
#define test_batch1 1
extern  void * test_batch1_1(char **, CLIENT *);
extern  void * test_batch1_1_svc(char **, struct svc_req *);
#define test_batch2 2
extern  void * test_batch2_1(char **, CLIENT *);
extern  void * test_batch2_1_svc(char **, struct svc_req *);
#define test_batch3 3
extern  void * test_batch3_1(char **, CLIENT *);
extern  void * test_batch3_1_svc(char **, struct svc_req *);
#define test_num_calls 4
extern  int * test_num_calls_1(void *, CLIENT *);
extern  int * test_num_calls_1_svc(void *, struct svc_req *);
extern int testprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define test_batch1 1
extern  void * test_batch1_1();
extern  void * test_batch1_1_svc();
#define test_batch2 2
extern  void * test_batch2_1();
extern  void * test_batch2_1_svc();
#define test_batch3 3
extern  void * test_batch3_1();
extern  void * test_batch3_1_svc();
#define test_num_calls 4
extern  int * test_num_calls_1();
extern  int * test_num_calls_1_svc();
extern int testprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_BATCH_H_RPCGEN */
