/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SSSON_H_RPCGEN
#define _SSSON_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct event {
	int event_id;
	char *desc;
};
typedef struct event event;

struct file {
	char *name;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct file file;

#define SSSONPROG 33330000
#define SSSONVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define send_event 1
extern  int * send_event_1(struct event *, CLIENT *);
extern  int * send_event_1_svc(struct event *, struct svc_req *);
#define send_file 2
extern  int * send_file_1(struct file *, CLIENT *);
extern  int * send_file_1_svc(struct file *, struct svc_req *);
#define rcv_event 3
extern  struct file * rcv_event_1(int *, CLIENT *);
extern  struct file * rcv_event_1_svc(int *, struct svc_req *);
extern int sssonprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send_event 1
extern  int * send_event_1();
extern  int * send_event_1_svc();
#define send_file 2
extern  int * send_file_1();
extern  int * send_file_1_svc();
#define rcv_event 3
extern  struct file * rcv_event_1();
extern  struct file * rcv_event_1_svc();
extern int sssonprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_event (XDR *, event*);
extern  bool_t xdr_file (XDR *, file*);

#else /* K&R C */
extern bool_t xdr_event ();
extern bool_t xdr_file ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SSSON_H_RPCGEN */
